# PATHS
additional_functions_file: ./main.py
output_path: ./
train_dataset: ./data/train
validation_dataset: ./data/validation

# OPTIMIZATION OPTIONS
loss: BinaryCrossentropy
optimizer:
  type: Adam
  learning_rate: 0.0001
metrics: [AUC]

# TRAINING OPTIONS
batch_size: 1
epochs: 1000
epoch_size: 100
shuffle_training_set: True
shuffle_validation_set: False
val_samples: 607
val_frequency: 1
execute_gpu: False
